name: Build TPFanController

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build TPFanController
        run: |
          msbuild fancontrol\fancontrol.sln /p:Configuration=Debug /p:Platform=Win32 /m

      - name: Show generated files
        shell: powershell
        run: |
          Get-ChildItem -Path . -Recurse -Filter *.exe |
          Select-Object FullName

      - name: Upload compiled program
        uses: actions/upload-artifact@v4
        with:
          name: TPFanController-Win32
          path: |
            fancontrol/Debug/**
          if-no-files-found: error
